openapi: 3.0.3
info:
  title: Client API of Halalz
  version: 1.0.0
servers:
  - url: https://api.halalz.org/api/v1
tags:
  - name: Auth
    description: Authentication API
  - name: Video
    description: API of Video
components:
  schemas:
    Video:
      type: object
      properties:
        id:
          type: string
          example: 5Ne-d-buzXA
        practicing_level:
          type: object
          properties:
            value:
              type: number
              enum:
                - 0: None/Haram
                - 1: All
                - 2: Male
                - 3: Female
                - 4: Child
                - -4: Except Child
            title:
              type: string
        permissible_for:
          type: object
          properties:
            value:
              type: number
              enum:
                - 0: None/Haram
                - 1: Practicing Muslim
                - 2: Liberal Muslim
                - 3: Moderate Muslim
            title:
              type: string
        is_halal:
          type: boolean
paths:
  /register:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: number
                email:
                  type: string
                name:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
  /login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      email:
                        type: string
                      name:
                        type: string
                  token:
                    type: string

  /videos:
    get:
      tags:
        - Video
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'
  /videos/{video}:
    get:
      tags:
        - Video
      parameters:
          - name: video
            in: path
            required: true
            schema:
              type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    items:
                      $ref: "#/components/schemas/Video"




